- name: Ensure baseline packages are installed
  ansible.builtin.dnf:
    name:
      - policycoreutils
      - policycoreutils-python-utils
      - firewalld
      - audit
      - chrony
      - zsh
      - tmux
      - neovim
      - fastfetch
      - git
      - ripgrep
      - fzf
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present

- name: Ensure chronyd is enabled (time sync)
  ansible.builtin.systemd:
    name: chronyd
    enabled: true
    state: started
